In [16]:
print("Hello")

Hello

In [17]:
import os

print(os.path.exists(
    '/Users/adityabohra/Desktop/customer shopping behaviour analysis'
))

False

In [18]:
import os

print(os.getcwd())

/Users/adityabohra/Desktop/customer shopping behaviour analysis

In [20]:
import os

print(os.listdir('.'))

['.DS_Store', '.ipynb_checkpoints', 'data cleaning.ipynb', 'raw']

In [21]:
import os

print(os.listdir('raw'))

['customer_shopping_behavior.csv']

In [22]:
df = pd.read_csv('raw/customer_shopping_behavior.csv')

In [23]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 835.9 KB

In [26]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [27]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [31]:
df['Review Rating'] = df groupby ('Category') ['Review Rating'].transform(lambda x: .fillna(x.median()))

SyntaxError: invalid syntax (715672498.py, line 1)

In [32]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(
    lambda x: x.fillna(x.median())
)

In [33]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [37]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [38]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [39]:
# Create a column age_group

labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']

df['age_group'] = pd.qcut(
    df['age'],
    q=4,
    labels=labels
)

In [40]:
df['age_group'].value_counts()

age_group
Young Adult    1028
Middle-aged     986
Senior          944
Adult           942
Name: count, dtype: int64

In [41]:
# Create column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [42]:
df['purchase_frequency_days'].value_counts()

purchase_frequency_days
90     1147
14     1089
365     572
30      553
7       539
Name: count, dtype: int64

In [43]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [44]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [45]:
df['frequency_of_purchases'].value_counts()

frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [46]:
df.drop('promo_code_used', axis=1, inplace=True)

In [47]:
%pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.14/site-packages (2.0.51)
Requirement already satisfied: pymysql in /opt/anaconda3/lib/python3.14/site-packages (1.2.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.14/site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [48]:
import pandas as pd
from sqlalchemy import create_engine

In [49]:
username = "root"
password = "1503"
host = "localhost"
port = 3306

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/"
)

In [50]:
from sqlalchemy import text

with engine.connect() as connection:
    connection.execute(text("CREATE DATABASE IF NOT EXISTS shopping_analysis"))

In [51]:
engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/shopping_analysis"
)

In [52]:
df.to_sql(
    name="customer_shopping",
    con=engine,
    if_exists="replace",
    index=False
)

3900

In [53]:
pd.read_sql("SELECT * FROM customer_shopping LIMIT 5", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [54]:
import pandas as pd

# Export the cleaned DataFrame to an Excel file
df.to_excel("cleaned.xlsx", index=False, sheet_name="cleaned")

print("File exported successfully as cleaned.xlsx")

File exported successfully as cleaned.xlsx

In [55]:
import os

print("File saved at:", os.path.abspath("cleaned.xlsx"))

File saved at: /Users/adityabohra/Desktop/customer shopping behaviour analysis /cleaned.xlsx